# -*- coding: utf-8 -*-
"""One-off rebuild of Business Math Unit 1 (course 456) content depth, per
Josh's feedback (2026-09-01):
  1. Reading pages were too shallow -- add more explanation, a second worked
     example, a common-mistakes callout, and an embedded Math Antics video.
  2. Worksheets were crooked textbook-scan images, not printable -- replaced
     with clean typeset PDFs (generated by worksheet_pdf.py / gen_all_worksheets.py)
     uploaded as real Canvas files and linked from the assignment.
  3. New: a "Want More Practice?" page at the end of each day linking to
     verified Math Antics videos + Khan Academy practice for that day's skills.

Uses targeted PUTs against already-live Pages/Assignments (matched by
url/id) rather than push_course.py, since the Practice quizzes (Day 1) and
Unit 1 Quiz/Test (Day 2) are unchanged and must not be touched or duplicated.
"""
import os
import sys
import requests
from dotenv import load_dotenv

sys.path.insert(0, "scripts")
from push_course import upload_file_to_canvas, add_to_module, HEADERS  # noqa: E402

load_dotenv()
BASE_URL = os.getenv("CANVAS_BASE_URL")
COURSE_ID = 456
WORKSHEETS_DIR = r"C:\Users\jball.VACE\Documents\Claude Projects\Claude Run Canvas\generated_worksheets"

DAY1_MODULE_ID = 2091
DAY2_MODULE_ID = 2092

# ---------------------------------------------------------------------------
# Design-system HTML helpers
# ---------------------------------------------------------------------------
WRAP_OPEN = '<div style="font-family:Arial,Helvetica,sans-serif;line-height:1.55;color:#1F2937;max-width:920px;margin:0 auto;">'
WRAP_CLOSE = '</div>'


def banner(eyebrow, title, subtitle):
    return (f'<div style="background:#003462;color:white;border-radius:4px;padding:20px 24px;margin:0 0 16px;">'
            f'<div style="font-size:12px;color:#FFCF01;">{eyebrow}</div>'
            f'<h1 style="margin:4px 0 4px;font-size:28px;line-height:1.15;color:white;">{title}</h1>'
            f'<div style="font-size:17px;line-height:1.35;color:#B5E3F0;">{subtitle}</div></div>')


def slim_header(label):
    return (f'<div style="background:#003462;color:white;border-radius:4px;padding:14px 20px;margin:0 0 16px;">'
            f'<div style="font-size:13px;letter-spacing:0.02em;color:#FFCF01;">{label}</div></div>')


def box(title, body_html, accent="teal"):
    color = "#00B7A3" if accent == "teal" else "#B5E3F0"
    h2 = f'<h2 style="font-size:20px;line-height:1.25;margin:0 0 10px;color:#003462;">{title}</h2>' if title else ""
    return (f'<div style="border-left:5px solid {color};background:#FFFFFF;border-top:1px solid #CBD5E1;'
            f'border-right:1px solid #CBD5E1;border-bottom:1px solid #CBD5E1;border-radius:4px;padding:16px 18px;margin:14px 0;">'
            f'{h2}{body_html}</div>')


def callout(label, text):
    return (f'<div style="background:#F5F7FA;border-left:5px solid #FFCF01;border-radius:4px;padding:12px 14px;margin:12px 0;">'
            f'<strong style="color:#003462;">{label}</strong><p style="margin:6px 0 0;">{text}</p></div>')


def meta_line(book_pages, cbo):
    return f'<p style="margin:0 0 10px;color:#003462;font-style:italic;font-size:13px;">Book pages: {book_pages} &middot; CBO Objective: {cbo}</p>'


def video_embed(video_id, title):
    return (f'<div style="margin:14px 0;"><div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;'
            f'border-radius:6px;border:1px solid #CBD5E1;"><iframe style="position:absolute;top:0;left:0;width:100%;height:100%;" '
            f'src="https://www.youtube.com/embed/{video_id}" title="{title}" allow="accelerometer; autoplay; clipboard-write; '
            f'encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy"></iframe></div>'
            f'<p style="margin:6px 0 0;font-size:12px;color:#6B7280;">Video: <em>{title}</em> (Math Antics, YouTube)</p></div>')


def pdf_link(label, url):
    return (f'<a href="{url}" style="display:inline-block;background:#003462;color:white;padding:8px 14px;'
            f'border-radius:4px;text-decoration:none;font-size:14px;">{label}</a>')


def api_get(endpoint, params=None):
    r = requests.get(f"{BASE_URL}{endpoint}", headers=HEADERS, params=params)
    return r.json()


def api_put(endpoint, data):
    r = requests.put(f"{BASE_URL}{endpoint}", headers=HEADERS, json=data)
    if r.status_code not in (200, 201):
        print(f"  ERROR {r.status_code}: {r.text[:300]}")
        return None
    return r.json()


def api_post(endpoint, data):
    r = requests.post(f"{BASE_URL}{endpoint}", headers=HEADERS, json=data)
    if r.status_code not in (200, 201):
        print(f"  ERROR {r.status_code}: {r.text[:300]}")
        return None
    return r.json()


def update_page(url_slug, body):
    print(f"  PUT page: {url_slug}")
    return api_put(f"/courses/{COURSE_ID}/pages/{url_slug}", {"wiki_page": {"body": body}})


def update_assignment(assignment_id, description):
    print(f"  PUT assignment: {assignment_id}")
    return api_put(f"/courses/{COURSE_ID}/assignments/{assignment_id}", {"assignment": {"description": description}})


import json

PDF_URLS_CACHE = os.path.join(WORKSHEETS_DIR, "pdf_urls.json")
with open(PDF_URLS_CACHE, encoding="utf-8") as f:
    PDF_URLS = json.load(f)
print(f"Loaded {len(PDF_URLS)} cached PDF URLs (already uploaded to course {COURSE_ID}).\n")

# ---------------------------------------------------------------------------
# Verified real YouTube video IDs (Math Antics channel, confirmed via oEmbed
# 2026-09-01 -- see checkpoint notes). Never guess a video ID.
# ---------------------------------------------------------------------------
V_PLACE_VALUE = "T5Qf0qSSJFI"
V_ROUNDING = "fd-E18EqSVk"
V_ADD_MULTI = "mAvuom42NyY"
V_SUB_MULTI = "Y6M89-6106I"
V_MULT_PT1 = "FJ5qLWP3Fqo"
V_MULT_PT2 = "RVYwunbpMHA"
V_DIV_LONG = "LGqBQrUYua4"
V_DIV_2DIGIT = "HdU_rf7eMTI"

# ===========================================================================
# DAY 1 READING PAGES (enhanced)
# ===========================================================================

place_value_body = slim_header("Day 1 &middot; Unit 1 Reading") + meta_line("7", "Identify place value") + (
    '<h2>Place Value</h2>'
    '<p>Whole numbers are made up of the <strong>digits</strong> 0, 1, 2, 3, 4, 5, 6, 7, 8, and 9. The number 44 has two digits. '
    'The number 23,060 has five digits. The value of each digit is different because of its position in the number. '
    'Every position has a <strong>place value</strong>.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0 0 8px;">Think of place value like money in your wallet: a $1 bill and a $100 bill both show the digit '
        '&ldquo;1&rdquo;, but their <em>position</em> (which bill they\'re printed on) makes them worth completely different amounts. '
        'Numbers work the same way &mdash; the digit 3 is worth 3, 30, 300, or 3,000,000 depending purely on which column it sits in.</p>'
        '<p style="margin:0;">Reading right to left, the columns go: units (ones), tens, hundreds, thousands, ten thousands, hundred '
        'thousands, millions &mdash; and the pattern of ones/tens/hundreds repeats inside every new group (thousands, millions, billions).</p>'
    ), accent="blue")
    + '<p><em>Example:</em> Find the value of 5 in 85,406.</p>'
    '<p>The digit 5 is in the thousands place. It has a value of 5 thousands, or 5,000.</p>'
    + box("A Second Example", '<p style="margin:0;"><em>Find the value of 7 in 2,573,940.</em><br>'
          'Counting from the right: 0 (ones), 4 (tens), 9 (hundreds), 3 (thousands), 7 (ten thousands). The 7 is in the '
          '<strong>ten thousands</strong> place, so its value is <strong>70,000</strong>.</p>')
    + callout("Common Mistakes to Avoid", (
        'Mixing up <em>place</em> and <em>value</em> is the #1 mix-up here: if asked for the <strong>value</strong> of the 5 in 85,406, '
        'the answer is <strong>5,000</strong> &mdash; not just &ldquo;5&rdquo; and not &ldquo;thousands.&rdquo; The place is the '
        'position\'s <em>name</em> (thousands); the value is what the digit is actually <em>worth</em> there (5,000). Also remember '
        'place values increase as you move right to left, not left to right.'
    ))
    + video_embed(V_PLACE_VALUE, "Math Antics - Place Value")
)

reading_writing_body = slim_header("Day 1 &middot; Unit 1 Reading") + meta_line("8-9", "Read and write whole numbers") + (
    '<h2>Reading and Writing Whole Numbers</h2>'
    '<p>Commas make numbers easier to read. Counting from the right, there is a comma after every three places. '
    'Large numbers are read in groups of three. At each comma we say the name of the group of digits that are set off by the comma.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0 0 8px;">Every number is really just a series of 3-digit &ldquo;chunks&rdquo; read one at a time, left to '
        'right, each chunk followed by its group name: <strong>...billion, million, thousand,</strong> (and then the last chunk has no '
        'name &mdash; it\'s just the ones/tens/hundreds).</p>'
        '<p style="margin:0;">So 12,050,006 breaks into three chunks: <strong>12</strong> | <strong>050</strong> | <strong>006</strong> '
        '&rarr; &ldquo;twelve <em>million</em>, fifty <em>thousand</em>, six.&rdquo; Notice the middle chunk\'s leading zero doesn\'t get '
        'read out loud &mdash; &ldquo;fifty,&rdquo; not &ldquo;zero-fifty.&rdquo;</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 2,043,000 is read: two <strong>million</strong>, forty-three <strong>thousand</strong>.</p>'
    '<p style="color:#003462;font-style:italic;">Notice how the commas go in the same place whether the number is written in words or figures.</p>'
    '<p>To write whole numbers from words, watch for places that must be held with zeros.</p>'
    '<p><em>Example:</em> Write &ldquo;three million, four hundred eight thousand, six hundred&rdquo; as a whole number.</p>'
    '<p>This number contains no ten thousands, no tens, and no units. Hold these places with zeros: <strong>3,408,600</strong>.</p>'
    + box("A Second Example", (
        '<p style="margin:0 0 8px;"><em>Write &ldquo;eight hundred thousand, forty&rdquo; as a whole number.</em><br>'
        'There\'s nothing in the hundred-thousands\' own hundreds/tens/ones (just &ldquo;800&rdquo; thousand), and nothing in the '
        'hundreds place of the last chunk &mdash; only tens and ones (&ldquo;40&rdquo;). Answer: <strong>800,040</strong>.</p>'
        '<p style="margin:0;"><em>Read 12,050,006.</em><br>Answer: <strong>twelve million, fifty thousand, six.</strong></p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'When writing a number FROM words, it\'s easy to drop a zero-holding place by accident &mdash; e.g. writing 3,48,600 instead '
        'of 3,408,600. After you write each chunk, count the digits: every chunk except possibly the very first must have exactly '
        'three digits. Also double-check comma placement lines up with your chunks, not with wherever feels natural.'
    ))
    + callout("Want a video for this one?", (
        'This skill is really place value applied to bigger numbers &mdash; if you want a refresher, revisit the Place Value video on '
        'the previous page, or check the Khan Academy link on the <strong>Want More Practice?</strong> page at the end of today.'
    ))
)

rounding_body = slim_header("Day 1 &middot; Unit 1 Reading") + meta_line("10-11", "Round whole numbers") + (
    '<h2>Rounding Whole Numbers</h2>'
    '<p>Cory&rsquo;s car weighs 2,374 pounds. What is the weight of her car to the nearest 100 pounds?</p>'
    '<p>To find the weight to the nearest 100 pounds, you must <em>round off</em> 2,374. Rounding makes numbers easier to use when you don&rsquo;t need exact values.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0 0 8px;">Rounding answers one question: &ldquo;what\'s the closest, simpler number I could use instead?&rdquo; '
        'It matters in real business situations &mdash; a manager quoting &ldquo;about $2,400&rdquo; instead of &ldquo;$2,374.18&rdquo; is '
        'rounding on purpose, because the exact cents rarely matter for a quick decision.</p>'
        '<p style="margin:0;">The whole rule boils down to looking at exactly <strong>one digit</strong> &mdash; the one immediately to '
        'the right of the place you\'re rounding to. That single digit decides whether your target digit stays the same or goes up by 1.</p>'
    ), accent="blue")
    + '<p>To round a whole number:</p>'
    '<ol style="margin:0 0 10px;padding-left:20px;">'
    '<li>Underline the digit in the place to which you want to round.</li>'
    '<li>If the digit to the right of the underlined digit is more than 4, add 1 to the underlined digit.</li>'
    '<li>If the digit to the right of the underlined digit is less than 5, do not change the underlined digit.</li>'
    '<li>Replace the digits to the right of the underlined digit with zeros.</li>'
    '</ol>'
    '<p><em>Example:</em> Round 2,374 to the nearest hundred.</p>'
    '<p><strong>Step 1.</strong> Underline the digit in the hundreds place, 3: 2,<u>3</u>74<br>'
    '<strong>Step 2.</strong> The digit to the right of 3 is 7. Add 1 to 3, and replace 7 and 4 with zeros: 2,400</p>'
    '<p>To the nearest 100 pounds, Cory&rsquo;s car weighs <strong>2,400</strong> pounds.</p>'
    '<p><em>Example:</em> Round 29,624 to the nearest thousand.</p>'
    '<p><strong>Step 1.</strong> Underline the digit in the thousands place, 9: 2<u>9</u>,624<br>'
    '<strong>Step 2.</strong> The digit to the right of 9 is 6. Add 1 to 9. Since 1 + 9 = 10, you must carry 1 over to the ten-thousands column. Replace 6, 2, and 4 with 0s: 30,000</p>'
    + box("A Third Example", (
        '<p style="margin:0;"><em>Round 6,382 to the nearest hundred.</em><br>'
        'The hundreds digit is 3. The digit to its right is 8 &mdash; more than 4, so round up: 3 becomes 4, and everything after it '
        'becomes zero. <strong>6,382 &rarr; 6,400</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'Only look at <strong>one</strong> digit &mdash; the one right after your target. Students sometimes glance at two or three '
        'digits and second-guess themselves; ignore everything except that single next digit. Also remember every digit to the right '
        'of your target becomes a zero, even if some of them were already going to &ldquo;round down&rdquo; on their own.'
    ))
    + video_embed(V_ROUNDING, "Math Antics - Rounding")
)

# ===========================================================================
# DAY 2 READING PAGES (enhanced)
# ===========================================================================

addition_carrying_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("11", "Add whole numbers with carrying") + (
    '<h2>Addition with Carrying</h2>'
    '<p>At the ABM Assembly plant there are 857 workers on the day-shift and 268 on the night shift. Find the total number of workers at ABM.</p>'
    '<p>The answer to an addition problem is called the <strong>sum</strong> or <strong>total</strong>. When the sum of the digits in a column '
    'is a two-digit number, <em>carry</em> the digit at the left to the next column to the left.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Carrying is just regrouping: if a column adds up to 10 or more, you\'re saying &ldquo;I have more ones than '
        'fit in this column, so I\'ll trade 10 of them for 1 of the next bigger unit.&rdquo; 15 ones = 1 ten + 5 ones &mdash; write the 5, '
        'carry the 1 ten into the tens column and add it in there.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 857 + 268 =</p>'
    '<p><strong>Step 1.</strong> Add the ones. 7 + 8 = 15. Write 5 under the ones column, and carry the 1 to the tens column.<br>'
    '<strong>Step 2.</strong> Add the tens. 1 + 5 = 6 and 6 + 6 = 12. Write the 2 under the tens and carry the 1 to the hundreds.<br>'
    '<strong>Step 3.</strong> Add the hundreds. 1 + 8 = 9 and 9 + 2 = 11.</p>'
    '<p>The total number of workers at ABM is <strong>1,125</strong>.</p>'
    + box("A Second Example (double carry)", (
        '<p style="margin:0;"><em>456 + 389 =</em><br>'
        'Ones: 6 + 9 = 15 &rarr; write 5, carry 1. Tens: 1 + 5 + 8 = 14 &rarr; write 4, carry 1. Hundreds: 1 + 4 + 3 = 8. '
        '<strong>Answer: 845</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'The most common slip is forgetting to actually <em>add</em> the carried digit once you move to the next column &mdash; write '
        'it small above the column as a reminder. If a column\'s total needs a 2-digit carry (like 29 &rarr; carry 2, not 1), make sure '
        'you carry the full amount, not just &ldquo;1&rdquo; out of habit.'
    ))
    + video_embed(V_ADD_MULTI, "Math Antics - Multi-Digit Addition")
)

addition_more_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("14", "Add more than two numbers") + (
    '<h2>Addition of More Than Two Numbers</h2>'
    '<p>Carlos works in the shipping department of an electrical supply company. For one customer he packed three boxes. One weighed 29 '
    'pounds, the second weighed 14 pounds, and the third weighed 7 pounds. Find the total weight of the three boxes.</p>'
    '<p>To add more than two numbers, find the total for each column. The digits in a column can be added in any order.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Same carrying rule as before &mdash; you\'re just adding <em>every</em> digit in the column before you '
        'carry, instead of only two. It can help to scan for pairs that make 10 first (like spotting 7 + 3) since adding those together '
        'first is often faster than working strictly top to bottom.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 29 + 14 + 7 =</p>'
    '<p><strong>Step 1.</strong> Line up the numbers and add the digits in the units column. 9 + 4 = 13. Then 13 + 7 = 20. Write 0 in the units '
    'column and carry 2 to the tens.<br>'
    '<strong>Step 2.</strong> Add the digits in the tens column. 2 + 2 = 4. Then 4 + 1 = 5.</p>'
    '<p>The total weight of the boxes is <strong>50</strong> pounds.</p>'
    + box("A Second Example", (
        '<p style="margin:0;"><em>148 + 26 + 375 =</em><br>'
        'Ones: 8 + 6 + 5 = 19 &rarr; write 9, carry 1. Tens: 1 + 4 + 2 + 7 = 14 &rarr; write 4, carry 1. Hundreds: 1 + 1 + 3 = 5. '
        '<strong>Answer: 549</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'With four, five, or more rows in a column, it\'s easy to lose your place and skip or double-count a digit &mdash; run your '
        'finger or pencil tip down the column as you add. And watch column sums of 20+: you may need to carry a 2, not just a 1.'
    ))
    + callout("Same skill, same video", (
        'This is the same carrying skill as the previous page &mdash; if you want to rewatch it, the Multi-Digit Addition video is on '
        'the &ldquo;Addition with Carrying&rdquo; reading, or linked again on the Want More Practice? page.'
    ))
)

subtraction_regrouping_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("16", "Subtract whole numbers with regrouping") + (
    '<h2>Subtraction with Regrouping</h2>'
    '<p>Carpenters at the ABM Company have to build 85 packing crates. By Wednesday they had finished 39 crates. How many do they have left?</p>'
    '<p>The answer to a subtraction problem is called the <strong>difference</strong>. When the bottom number in any column is too large to '
    'subtract from the top number, you must <strong>regroup</strong> the top number. You may know this operation as <em>renaming</em> or '
    '<em>borrowing</em>.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Borrowing is carrying in reverse: when a column doesn\'t have enough to subtract, you break open 1 unit from '
        'the column to its left and turn it into 10 of the smaller unit. Borrow 1 ten &rarr; it becomes 10 ones added to what\'s already '
        'there. The column you borrowed <em>from</em> goes down by 1.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 85 &minus; 39 =</p>'
    '<p><strong>Step 1.</strong> 9 is too large to subtract from 5. Regroup the top number: take 1 ten from the tens column (8 &minus; 1 = 7) '
    'and add it to the units (10 + 5 = 15).<br>'
    '<strong>Step 2.</strong> Subtract the units. 15 &minus; 9 = 6.<br>'
    '<strong>Step 3.</strong> Subtract the tens. 7 &minus; 3 = 4.</p>'
    '<p>The carpenters have <strong>46</strong> crates left to build.</p>'
    + box("A Second Example", (
        '<p style="margin:0;"><em>63 &minus; 28 =</em><br>'
        '8 is too big to take from 3, so borrow: 6 tens &rarr; 5 tens, and the 3 ones become 13 ones. 13 &minus; 8 = 5. Then 5 tens &minus; 2 '
        'tens = 3. <strong>Answer: 35</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'The classic early-learner error is subtracting the smaller digit from the larger one <em>regardless of which is on top</em> '
        '(e.g. doing 9 &minus; 5 instead of borrowing, just because 9 is bigger) &mdash; always check whether the TOP digit is big enough '
        'first. And after you borrow from a column, don\'t forget to actually reduce that column by 1 before you get to it.'
    ))
    + video_embed(V_SUB_MULTI, "Math Antics - Multi-Digit Subtraction")
)

regrouping_zeros_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("18", "Regroup with zeros") + (
    '<h2>Regrouping with Zeros</h2>'
    '<p>Imani had $904 in her savings account. She withdrew $356 to buy new winter clothes. How much did she have left in her account?</p>'
    '<p>To regroup with zeros, look at the first digit in the top number that is not zero.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Normally you borrow from the very next column over. But if that column is a <strong>zero</strong>, there\'s '
        'nothing there to borrow &mdash; so you have to reach further left to the first non-zero digit, borrow from it, and then '
        '&ldquo;cascade&rdquo; that borrow back down through every zero in between (each zero becomes a 9, except the very last one, which '
        'becomes 10 and combines with the ones column).</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 904 &minus; 356 =</p>'
    '<p><strong>Step 1.</strong> You cannot subtract 6 from 4. Take 1 hundred from the hundreds column (9 &minus; 1 = 8). You now have 10 tens '
    'in the tens column.<br>'
    '<strong>Step 2.</strong> Take 1 ten from the 10 in the tens column (10 &minus; 1 = 9) and add it to the units (10 + 4 = 14).<br>'
    '<strong>Step 3.</strong> Subtract the units. 14 &minus; 6 = 8.<br>'
    '<strong>Step 4.</strong> Subtract the tens. 9 &minus; 5 = 4.<br>'
    '<strong>Step 5.</strong> Subtract the hundreds. 8 &minus; 3 = 5.</p>'
    '<p>Imani had <strong>$548</strong> left in her account.</p>'
    + box("A Second Example (single zero)", (
        '<p style="margin:0;"><em>500 &minus; 247 =</em><br>'
        'The tens column is 0, so reach to the hundreds: 5 &rarr; 4, and that 1 hundred becomes 10 tens. Now borrow 1 ten for the ones: '
        '10 tens &rarr; 9 tens, and the ones become 10. 10 &minus; 7 = 3. 9 &minus; 4 = 5. 4 &minus; 2 = 2. <strong>Answer: 253</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'With more than one zero in a row (like 4,000 &minus; 1,256), the cascade has to pass through <em>every</em> zero &mdash; stopping '
        'the borrow too early is the #1 error here. Each zero you pass through becomes a 9; only the very last one becomes 10.'
    ))
    + callout("Same skill, same video", (
        'This builds directly on the Multi-Digit Subtraction video from the previous page &mdash; rewatch it if the zero-cascade felt '
        'shaky, and try the practice problems on the Want More Practice? page.'
    ))
)

multiplication_carrying_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("20", "Multiply whole numbers with carrying") + (
    '<h2>Multiplication with Carrying</h2>'
    '<p>The shipping department at Ace Electrical sent out 29 crates of motor parts. Each crate weighed 76 pounds. Find the total weight of '
    'the shipment.</p>'
    '<p>The answer to a multiplication problem is called the <em>product</em>. When you multiply two digits, the product is often a two-digit '
    'number. You must <strong>carry</strong> the left digit to the next number you are multiplying. Then <strong>add</strong> the digit you '
    'carry to the next product.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Multiplying by a 2-digit number is really two smaller multiplications added together, called '
        '<strong>partial products</strong>: first multiply by the ones digit, then multiply by the tens digit (writing that second row '
        'shifted one place to the left, since you\'re really multiplying by a number of tens). Add the two partial products for your final '
        'answer.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 76 &times; 29 =</p>'
    '<p><strong>Step 1.</strong> 9 &times; 6 = 54. Write 4 in the units column, and carry 5 to the next column.<br>'
    '<strong>Step 2.</strong> 9 &times; 7 = 63. Add the 5 you carried: 63 + 5 = 68.<br>'
    '<strong>Step 3.</strong> 2 &times; 6 = 12. Write 2 in the tens column, carry the 1 to the next column.<br>'
    '<strong>Step 4.</strong> 2 &times; 7 = 14. Add the 1 you carried: 14 + 1 = 15.<br>'
    '<strong>Step 5.</strong> Add the partial products.</p>'
    '<p>The total weight of the shipment was <strong>2,204</strong> pounds.</p>'
    + box("A Second Example (with partial products shown)", (
        '<p style="margin:0;"><em>58 &times; 43 =</em><br>'
        'Partial product 1 (58 &times; 3): 174. Partial product 2 (58 &times; 4, shifted one place left because it\'s really &times;40): '
        '2,320. Add: 174 + 2,320 = <strong>2,494</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'The #1 error is forgetting to shift the second partial product one place to the left (or forgetting its placeholder zero) '
        '&mdash; that shift is what makes it &times;40 instead of &times;4. Also watch for carrying mistakes inside a single partial '
        'product, same as regular multi-digit multiplication.'
    ))
    + video_embed(V_MULT_PT1, "Math Antics - Multi-Digit Multiplication Pt 1")
    + video_embed(V_MULT_PT2, "Math Antics - Multi-Digit Multiplication Pt 2")
)

division_one_digit_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("22-23", "Divide by one digit") + (
    '<h2>Division by One Digit</h2>'
    '<p>Serena has a part-time job at a convenience store. She makes $6 an hour. Last month she made $504. How many hours did she work?</p>'
    '<p>The answer to a division problem is called the <strong>quotient</strong>. To find a quotient, repeat these four steps until you '
    'complete the problem: 1. Divide. 2. Multiply. 3. Subtract and compare. 4. Bring down the next number.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Long division is really a sequence of small &ldquo;how many times does this fit?&rdquo; questions, worked '
        'one digit at a time from left to right. Each round follows the same 4-step cycle (Divide &rarr; Multiply &rarr; Subtract &rarr; '
        'Bring down) until there are no more digits left to bring down.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> Divide 6 into 504.</p>'
    '<p><strong>Step 1.</strong> Divide: 6 goes into 50 eight times. Write 8 above the tens place.<br>'
    '<strong>Step 2.</strong> Multiply: 8 &times; 6 = 48. Write 48 under 50.<br>'
    '<strong>Step 3.</strong> Subtract: 50 &minus; 48 = 2. Compare to be sure 2 is less than 6.<br>'
    '<strong>Step 4.</strong> Bring down the next number: 4.<br>'
    '<strong>Step 5.</strong> Divide: 6 goes into 24 four times. Write 4 above the units place.<br>'
    '<strong>Step 6.</strong> Multiply: 4 &times; 6 = 24. Write 24 under 24.<br>'
    '<strong>Step 7.</strong> Subtract: 24 &minus; 24 = 0. Compare: 0 is less than 6.</p>'
    '<p>Serena worked <strong>84</strong> hours.</p>'
    '<p>Writing every step is called <strong>long division</strong>. In <strong>short division</strong> you write only the answer and the '
    'number you get by subtracting.</p>'
    + box("A Second Example", (
        '<p style="margin:0;"><em>Divide 4 into 372.</em><br>'
        '4 goes into 37 nine times (9&times;4=36, remainder 1). Bring down the 2 &rarr; 12. 4 goes into 12 three times exactly. '
        '<strong>Answer: 93</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'Writing the quotient digit above the wrong column is the most common slip &mdash; each digit you write goes directly above the '
        'digit you just brought down. And don\'t skip bringing down the next digit before continuing; that\'s what tells you when the '
        'problem is finished.'
    ))
    + video_embed(V_DIV_LONG, "Math Antics - Long Division")
)

division_remainders_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("24", "Divide with remainders") + (
    '<h2>Division with Remainders</h2>'
    '<p>How many buckets, each containing 4 quarts of paint, can Alan fill from a vat that contains 387 quarts of paint?</p>'
    '<p>If you do not get zero in the last subtraction step of a division problem, you will have a <strong>remainder</strong>.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0 0 8px;">A remainder is simply whatever\'s left over that doesn\'t divide evenly. What you <em>do</em> with a '
        'remainder in a real business problem depends on context: if you\'re asking &ldquo;how many full buckets,&rdquo; you drop the '
        'remainder (it\'s the leftover paint, not another bucket). But if the question were &ldquo;how many buckets do I need to buy to '
        'hold ALL the paint,&rdquo; you\'d round <em>up</em> even with a remainder, since a partly-full bucket still counts as one you need.</p>'
        '<p style="margin:0;">In this unit, just report the remainder as-is (written &ldquo;r&rdquo; followed by the leftover number) unless '
        'a problem specifically asks you to interpret it.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> 387 &divide; 4 = 96r3</p>'
    '<p>Alan can fill 96 buckets. There will be 3 quarts left over.</p>'
    '<p>If a division problem is written with the &divide; sign, rewrite the problem using the long-division bracket before dividing.</p>'
    + box("A Second Example", (
        '<p style="margin:0;"><em>260 &divide; 7 =</em><br>'
        '7 goes into 26 three times (3&times;7=21, remainder 5). Bring down the 0 &rarr; 50. 7 goes into 50 seven times (7&times;7=49, '
        'remainder 1). <strong>Answer: 37r1</strong>.</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'Your remainder should always be <strong>smaller</strong> than the number you\'re dividing by &mdash; if it isn\'t, that\'s a sign '
        'your last &ldquo;divide&rdquo; step guessed too low and you need to go one higher. And don\'t forget to write the remainder at all '
        '&mdash; &ldquo;96&rdquo; and &ldquo;96r3&rdquo; are different answers.'
    ))
    + callout("Same skill, same video", (
        'This is the same long-division process from the previous page, just with problems that don\'t divide evenly &mdash; rewatch the '
        'Long Division video there if you need it.'
    ))
)

division_larger_body = slim_header("Day 2 &middot; Unit 1 Reading") + meta_line("26", "Divide by larger numbers") + (
    '<h2>Division by Larger Numbers</h2>'
    '<p>Sonny borrowed $2,976. He is paying back $62 a month. How many months will he need to repay the entire loan?</p>'
    '<p>To divide by two-digit and three-digit numbers, you must <strong>estimate</strong> how many times one number divides into another '
    'number. When you estimate, you make a guess.</p>'
    + box("Breaking It Down", (
        '<p style="margin:0;">Dividing by a bigger number means you usually can\'t just &ldquo;know&rdquo; the answer from memorized facts '
        '&mdash; you <strong>estimate</strong> (often by looking at just the lead digits), then <strong>check</strong> your estimate by '
        'multiplying back out, and <strong>adjust</strong> up or down if it was wrong. This estimate-check-adjust loop is the whole skill; '
        'don\'t expect to get every estimate right on the first try.</p>'
    ), accent="blue")
    + '<p><em>Example:</em> Divide 2,976 by 62.</p>'
    '<p><strong>Step 1.</strong> Estimate how many times 62 divides into 297: ask how many times 6 divides into 29 (29 &divide; 6 = 4 plus a '
    'remainder). Write 4 above the 7.<br>'
    '<strong>Step 2.</strong> Multiply: 4 &times; 62 = 248. Write 248 under 297.<br>'
    '<strong>Step 3.</strong> Subtract: 297 &minus; 248 = 49, and compare: 49 is less than 62.<br>'
    '<strong>Step 4.</strong> Bring down the next number: 6.<br>'
    '<strong>Step 5.</strong> Estimate how many times 62 divides into 496: ask how many times 6 goes into 49 (49 &divide; 6 = 8 plus a '
    'remainder). Write 8 above the 6.<br>'
    '<strong>Step 6.</strong> Multiply: 8 &times; 62 = 496. Write 496 under 496.<br>'
    '<strong>Step 7.</strong> Subtract: 496 &minus; 496 = 0.<br>'
    '<strong>Step 8.</strong> Check: 48 &times; 62 = 2,976.</p>'
    '<p>Sonny will need <strong>48</strong> months to repay the loan.</p>'
    '<p style="color:#003462;font-style:italic;">Sometimes your first estimate will be wrong. Work with a pencil and a good eraser. Decide if '
    'your estimate is too small or too large and try again.</p>'
    + box("A Second Example (adjusting an estimate)", (
        '<p style="margin:0;"><em>1,464 &divide; 24 =</em><br>'
        'Estimate: 24 into 146 &mdash; try 6 (6&times;24=144, remainder 2, works). Bring down the 4 &rarr; 24. 24 goes into 24 exactly once. '
        '<strong>Answer: 61</strong>. (If you\'d first guessed 7, 7&times;24=168 is too big &mdash; that\'s the &ldquo;adjust down&rdquo; '
        'moment this skill is all about.)</p>'
    ))
    + callout("Common Mistakes to Avoid", (
        'Always <strong>verify</strong> an estimate by multiplying it back out before moving on &mdash; if the remainder you get is bigger '
        'than the divisor, your estimate was too low and needs to go up by 1 (or more). Don\'t just accept the first guess without checking.'
    ))
    + video_embed(V_DIV_2DIGIT, "Math Antics - Long Division with 2-Digit Divisors")
)

# ===========================================================================
# WORKSHEET ASSIGNMENTS -- rebuilt to link the clean PDFs instead of the
# crooked scan images
# ===========================================================================

def worksheet_description(ws_title, book_pages, pdf_name, ans_pdf_name):
    pdf_url = PDF_URLS[pdf_name]
    ans_url = PDF_URLS[ans_pdf_name]
    return (
        WRAP_OPEN
        + banner("Day 2 &middot; Unit 1 Worksheet", ws_title, f"Self-check practice &mdash; not graded. Book pages {book_pages}.")
        + box("", (
            '<p style="margin:0 0 12px;">This worksheet is a clean, printable PDF (typeset from the book\'s own problems) &mdash; '
            'print it, work it on paper with your calculator, then check the Answer Key below before moving on.</p>'
            f'{pdf_link("Download Worksheet (PDF)", pdf_url)}'
        ))
        + f'<details style="margin-top:14px;"><summary style="cursor:pointer;color:#003462;font-weight:bold;">Answer Key</summary>'
          f'<div style="margin-top:10px;">{pdf_link("Download Answer Key (PDF)", ans_url)}</div></details>'
        + WRAP_CLOSE
    )


review_description = (
    WRAP_OPEN
    + banner("Day 2 &middot; Unit 1 Self-Paced Practice", "Whole Numbers Review", "Self-check &mdash; not graded. Book pages 28-29.")
    + box("", (
        '<p style="margin:0 0 12px;">These problems cover everything in Unit 1. Print the PDF, solve each problem, then check your '
        'answers against the Answer Key. Revisit any topic\'s reading page for problems you miss before moving on to the Unit 1 Quiz.</p>'
        f'{pdf_link("Download Whole Numbers Review (PDF)", PDF_URLS["Whole Numbers Review.pdf"])}'
    ))
    + f'<details style="margin-top:14px;"><summary style="cursor:pointer;color:#003462;font-weight:bold;">Answer Key</summary>'
      f'<div style="margin-top:10px;">{pdf_link("Download Answer Key (PDF)", PDF_URLS["Whole Numbers Review Answer Key.pdf"])}</div></details>'
    + WRAP_CLOSE
)

# ===========================================================================
# "WANT MORE PRACTICE?" PAGES (new, one per day)
# ===========================================================================

def resource_list(items):
    lis = "".join(
        f'<li style="margin-bottom:10px;"><a href="{url}" style="color:#003462;font-weight:bold;">{title}</a>'
        f'<br><span style="font-size:13px;color:#4B5563;">{desc}</span></li>'
        for title, url, desc in items
    )
    return f'<ul style="margin:0;padding-left:20px;">{lis}</ul>'


day1_practice_body = (
    WRAP_OPEN
    + banner("Day 1 &middot; Unit 1", "Want More Practice?", "Optional extra videos and practice for today's skills &mdash; use these if you want more repetition before Day 2.")
    + box("Place Value", resource_list([
        ("Math Antics - Place Value (video)", f"https://www.youtube.com/watch?v={V_PLACE_VALUE}",
         "Same video embedded on the Place Value reading, in case you want it full-screen."),
        ("Khan Academy - Place Value practice", "https://www.khanacademy.org/math/arithmetic-home/arith-place-value",
         "Free interactive practice: identifying place value, writing numbers in different forms, and more."),
    ]))
    + box("Reading and Writing Whole Numbers", resource_list([
        ("Khan Academy - Whole number place value review", "https://www.khanacademy.org/math/arithmetic-home/arith-place-value/arith-intro-to-place-value/a/whole-number-place-value-review",
         "A short article + practice covering reading and writing large numbers."),
    ]), accent="blue")
    + box("Rounding", resource_list([
        ("Math Antics - Rounding (video)", f"https://www.youtube.com/watch?v={V_ROUNDING}",
         "Same video embedded on the Rounding reading."),
        ("Khan Academy - Round whole numbers practice", "https://www.khanacademy.org/math/arithmetic-home/arith-place-value/arith-rounding-whole/e/rounding_whole_numbers",
         "Interactive rounding drills with instant feedback."),
    ]))
    + WRAP_CLOSE
)

day2_practice_body = (
    WRAP_OPEN
    + banner("Day 2 &middot; Unit 1", "Want More Practice?", "Optional extra videos and practice for today's skills.")
    + box("Addition &amp; Subtraction", resource_list([
        ("Math Antics - Multi-Digit Addition (video)", f"https://www.youtube.com/watch?v={V_ADD_MULTI}", "Carrying, explained step by step."),
        ("Math Antics - Multi-Digit Subtraction (video)", f"https://www.youtube.com/watch?v={V_SUB_MULTI}", "Regrouping/borrowing, including zeros."),
        ("Khan Academy - Add and subtract through 1,000,000", "https://www.khanacademy.org/math/arithmetic/addition-subtraction/two_dig_add_sub",
         "Practice sets for multi-digit addition and subtraction, including regrouping."),
    ]))
    + box("Multiplication", resource_list([
        ("Math Antics - Multi-Digit Multiplication Pt 1 (video)", f"https://www.youtube.com/watch?v={V_MULT_PT1}", "Single-digit multiplier, with carrying."),
        ("Math Antics - Multi-Digit Multiplication Pt 2 (video)", f"https://www.youtube.com/watch?v={V_MULT_PT2}", "Two-digit multiplier and partial products."),
    ]), accent="blue")
    + box("Division", resource_list([
        ("Math Antics - Long Division (video)", f"https://www.youtube.com/watch?v={V_DIV_LONG}", "The core divide-multiply-subtract-bring down cycle."),
        ("Math Antics - Long Division with 2-Digit Divisors (video)", f"https://www.youtube.com/watch?v={V_DIV_2DIGIT}", "Estimating when the divisor has 2+ digits."),
        ("Khan Academy - Multiplication and division", "https://www.khanacademy.org/math/arithmetic-home/arithmetic/arith-review-multiply-divide",
         "General multiply/divide practice hub."),
        ("Khan Academy - Division by 2-digits practice", "https://www.khanacademy.org/math/arithmetic-home/multiply-divide/mult-digit-div-2/e/division_3",
         "Practice dividing by larger numbers, matching Worksheet 11."),
    ]))
    + WRAP_CLOSE
)

# ===========================================================================
# EXECUTE
# ===========================================================================

if __name__ == "__main__":
    print("Updating Day 1 reading pages...")
    update_page("place-value-reading", place_value_body)
    update_page("reading-and-writing-whole-numbers-reading", reading_writing_body)
    update_page("rounding-whole-numbers-reading", rounding_body)
    
    print("\nUpdating Day 2 reading pages...")
    update_page("addition-with-carrying-reading", addition_carrying_body)
    update_page("addition-of-more-than-two-numbers-reading", addition_more_body)
    update_page("subtraction-with-regrouping-reading", subtraction_regrouping_body)
    update_page("regrouping-with-zeros-reading", regrouping_zeros_body)
    update_page("multiplication-with-carrying-reading", multiplication_carrying_body)
    update_page("division-by-one-digit-reading", division_one_digit_body)
    update_page("division-with-remainders-reading", division_remainders_body)
    update_page("division-by-larger-numbers-reading", division_larger_body)
    
    print("\nUpdating Day 2 worksheet assignments...")
    update_assignment(8688, worksheet_description("Worksheet 4: Addition with Carrying", "12-13",
                       "Worksheet 4: Addition with Carrying.pdf", "Worksheet 4 Answer Key.pdf"))
    update_assignment(8689, worksheet_description("Worksheet 5: Addition of More Than Two Numbers", "14-15",
                       "Worksheet 5: Addition of More Than Two Numbers.pdf", "Worksheet 5 Answer Key.pdf"))
    update_assignment(8690, worksheet_description("Worksheet 6: Subtraction with Regrouping", "16-17",
                       "Worksheet 6: Subtraction with Regrouping.pdf", "Worksheet 6 Answer Key.pdf"))
    update_assignment(8691, worksheet_description("Worksheet 7: Regrouping with Zeros", "18-19",
                       "Worksheet 7: Regrouping with Zeros.pdf", "Worksheet 7 Answer Key.pdf"))
    update_assignment(8692, worksheet_description("Worksheet 8: Multiplication with Carrying", "20-21",
                       "Worksheet 8: Multiplication with Carrying.pdf", "Worksheet 8 Answer Key.pdf"))
    update_assignment(8693, worksheet_description("Worksheet 9: Division by One Digit", "22-23",
                       "Worksheet 9: Division by One Digit.pdf", "Worksheet 9 Answer Key.pdf"))
    update_assignment(8694, worksheet_description("Worksheet 10: Division with Remainders", "24-25",
                       "Worksheet 10: Division with Remainders.pdf", "Worksheet 10 Answer Key.pdf"))
    update_assignment(8695, worksheet_description("Worksheet 11: Division by Larger Numbers", "26-27",
                       "Worksheet 11: Division by Larger Numbers.pdf", "Worksheet 11 Answer Key.pdf"))
    update_assignment(8696, review_description)
    
    print("\nAdding 'Want More Practice?' pages...")
    p1 = api_post(f"/courses/{COURSE_ID}/pages", {"wiki_page": {"title": "Day 1: Want More Practice?", "body": day1_practice_body, "published": False}})
    if p1:
        add_to_module(COURSE_ID, DAY1_MODULE_ID, "Page", page_url=p1["url"], title="Day 1: Want More Practice?")
        print(f"  + Day 1: Want More Practice? ({p1['url']})")
    
    p2 = api_post(f"/courses/{COURSE_ID}/pages", {"wiki_page": {"title": "Day 2: Want More Practice?", "body": day2_practice_body, "published": False}})
    if p2:
        add_to_module(COURSE_ID, DAY2_MODULE_ID, "Page", page_url=p2["url"], title="Day 2: Want More Practice?")
        print(f"  + Day 2: Want More Practice? ({p2['url']})")
    
    print("\nDone.")
